//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula240521
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SERVICO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> dataServico { get; set; }
        public Nullable<System.DateTime> dataPrevistaConclusaoServico { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_tipo_servico { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_TIPO_SERVICO TB_TIPO_SERVICO { get; set; }
    }
}
